### ISSUE TITLE
Results do not correspond to current coco set

### ISSUE THREAD

**Issue by DrawingWorkerChi** [PatBall1/detectree2#133]
Hello, thank you for your contribution. During my training, I encountered the following error message, which seems to be due to image_ id is not of type int. I go check the image_id which is the absolute path of the image and is of type string. Is there any way to solve it? thanks！

Exception during training:
Traceback (most recent call last):
  File "E:\somedata\detectree2-master\detectree2\models\train.py", line 210, in train
    self.after_step()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\train_loop.py", line 190, in after_step
    h.after_step()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\hooks.py", line 556, in after_step
    self._do_eval()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\hooks.py", line 529, in _do_eval
    results = self._func()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\defaults.py", line 455, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\defaults.py", line 619, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\evaluation\evaluator.py", line 213, in inference_on_dataset
    results = evaluator.evaluate()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\evaluation\coco_evaluation.py", line 206, in evaluate
    self._eval_predictions(predictions, img_ids=img_ids)
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\evaluation\coco_evaluation.py", line 266, in _eval_predictions
    _evaluate_predictions_on_coco(
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\evaluation\coco_evaluation.py", line 590, in _evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(coco_results)
  File "D:\Anaconda\envs\DL\lib\site-packages\pycocotools\coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set
Traceback (most recent call last):
  File "E:\somedata\detectree2-master\detectree2\models\train.py", line 210, in train
    self.after_step()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\train_loop.py", line 190, in after_step
    h.after_step()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\hooks.py", line 556, in after_step
    self._do_eval()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\hooks.py", line 529, in _do_eval
    results = self._func()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\defaults.py", line 455, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\defaults.py", line 619, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\evaluation\evaluator.py", line 213, in inference_on_dataset
    results = evaluator.evaluate()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\evaluation\coco_evaluation.py", line 206, in evaluate
    self._eval_predictions(predictions, img_ids=img_ids)
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\evaluation\coco_evaluation.py", line 266, in _eval_predictions
    _evaluate_predictions_on_coco(
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\evaluation\coco_evaluation.py", line 590, in _evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(coco_results)
  File "D:\Anaconda\envs\DL\lib\site-packages\pycocotools\coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\somedata\detectree2-master\detectree2\models\train.py", line 662, in <module>
    trainer.train()
  File "E:\somedata\detectree2-master\detectree2\models\train.py", line 221, in train
    self.after_train()
  File "D:\Anaconda\envs\DL\lib\site-packages\detectron2-0.6-py3.9-win-amd64.egg\detectron2\engine\train_loop.py", line 174, in after_train
    h.after_train()
  File "E:\somedata\detectree2-master\detectree2\models\train.py", line 159, in after_train
    index = self.trainer.APs.index(max(self.trainer.APs)) + 1
ValueError: max() arg is an empty sequence

Process finished with exit code 1

**Comment by PatBall1** [comment]
Hi Chi, thanks for raising this issue. I would be helpful to get a few more details before I investigate.

- What code did you run to get the error?
- Which system you are working on?

It appears that you have set up the package on Windows. We don't yet support Windows (we advise linux or Google Colab). My initial guess is that there may be a simple mix up of "\" and "/" coming from the different way paths are specified in Windows.

**Comment by DrawingWorkerChi** [comment]
Thank you for your reply. I encountered the following error after running train.py and I am running it on a Windows system. My next step will be to try running on Linux.

**Comment by DrawingWorkerChi** [comment]
Thank you for your help.  I successfully ran the program！
