### ISSUE TITLE
Regarding self-made datasets

### ISSUE THREAD

**Issue by DrawingWorkerChi** [PatBall1/detectree2#138]
May I ask how you create dataset annotations? I used QGIS to annotate the tree crown and exported it in gpkg format, but encountered an error while reading.Thank you very much！

Traceback (most recent call last):
  File "E:\somedata\detectree2-master\about_qiushu\tile_qiushu.py", line 71, in <module>
    crowns = gpd.read_file(crown_path)
  File "D:\Anaconda\envs\DL\lib\site-packages\geopandas\io\file.py", line 297, in _read_file
    return _read_file_fiona(
  File "D:\Anaconda\envs\DL\lib\site-packages\geopandas\io\file.py", line 386, in _read_file_fiona
    columns = list(features.schema["properties"])
  File "D:\Anaconda\envs\DL\lib\site-packages\fiona\collection.py", line 284, in schema
    self._schema = self.session.get_schema()
  File "fiona\ogrext.pyx", line 827, in fiona.ogrext.Session.get_schema
  File "fiona\_geometry.pyx", line 54, in fiona._geometry.normalize_geometry_type_code
fiona.errors.UnsupportedGeometryTypeError: 10

Process finished with exit code 1

**Comment by PatBall1** [comment]
Hi @DrawingWorkerChi , thanks for raising this issue.
Your error suggests that you created a geometry type in QGIS that is incompatible with fiona.
Specifically, `fiona.errors.UnsupportedGeometryTypeError: 10` suggests that you have created a "CurvePolygon". Can you check your geometries and see if this is correct?
I would suggest sticking with normal polygons for tree crowns.

**Comment by DrawingWorkerChi** [comment]
Thank you for your reply. It is indeed due to the issue with the polygon, thank you again!
