### ISSUE TITLE
KeyError: 'D' in training process

### ISSUE THREAD

**Issue by ambarwariagus** [PatBall1/detectree2#161]
I have installed detectree2 on anaconda windows and it works for prediction. However, during the training process I encountered `KeyError: 'D'`. I am currently using the Danum dataset, and following the instructions as per the manual provided.
Does anyone have a solution to this problem?

Here is my program code:
```
from detectree2.preprocessing.tiling import tile_data, to_traintest_folders
from detectree2.models.train import register_train_data, MyTrainer, setup_cfg
import rasterio
import geopandas as gpd

# Set up input paths Danum
site_path = "D:/DATASET/detectree2-dataset/Danum"
img_path = site_path + "/rgb/Dan_2014_RGB_project_to_CHM.tif"
crown_path = site_path + "/crowns/Danum.gpkg"

# Read in the tiff file
data = rasterio.open(img_path)

# Read in crowns (then filter by an attribute if required)
crowns = gpd.read_file(crown_path)
crowns = crowns.to_crs(data.crs.data) # making sure CRS match

# Set tiling parameters (default, 30, 40, 40)
buffer = 30
tile_width = 40
tile_height = 40
threshold = 0.6
appends = str(tile_width) + "_" + str(buffer) + "_" + str(threshold) # this helps keep file structure organised
out_dir = site_path + "/tiles_" + appends + "/"

tile_data(img_path, out_dir, buffer, tile_width, tile_height, crowns, threshold, mode="rgb")

data_folder = out_dir # data_folder is the folder where the .png, .tif, .geojson tiles have been stored
to_traintest_folders(data_folder, out_dir, test_frac=0.15, strict=True, folds=3)

train_location = "D:/DATASET/detectree2-dataset/Danum/tiles_" + appends + "/train/"
register_train_data(train_location, 'Danum', val_fold=3)

# Set the base (pre-trained) model from the detectron2 model_zoo
base_model = "COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml"

# Set the updated model weights from the detectree2 pre-trained model
# trained_model = "D:/AI_MODELS/detectree2-models/230103_randresize_full.pth"

trains = ("Danum_train") # Registered train data
tests = ("Danum_val") # Registered validation data

out_dir = "D:/DATASET/detectree2-dataset/240809_train_outputs"

cfg = setup_cfg(base_model, trains, tests, workers=4, eval_period=100, max_iter=3000, out_dir=out_dir) # update_model arg can be used to load in trained  model

trainer = MyTrainer(cfg, patience=5)
trainer.resume_or_load(resume=False)
trainer.train()
```

The outputs are as follows:
```
INFO:detectron2.engine.defaults:Model:
GeneralizedRCNN(
 ...
INFO:detectron2.data.dataset_mapper:[DatasetMapper] Augmentations used in training: [RandomRotation(angle=[0, 360], expand=False), RandomFlip(prob=0.5), RandomBrightness(intensity_min=0.7, intensity_max=1.5), RandomLighting(scale=0.7), RandomContrast(intensity_min=0.6, intensity_max=1.3), RandomSaturation(intensity_min=0.8, intensity_max=1.4), ResizeShortestEdge(short_edge_length=[1000, 1000], max_size=1333)]
INFO:__main__:[FlexibleDatasetMapper] Augmentations used in training: [RandomRotation(angle=[0, 360], expand=False), RandomFlip(prob=0.5), RandomBrightness(intensity_min=0.7, intensity_max=1.5), RandomLighting(scale=0.7), RandomContrast(intensity_min=0.6, intensity_max=1.3), RandomSaturation(intensity_min=0.8, intensity_max=1.4), ResizeShortestEdge(short_edge_length=[1000, 1000], max_size=1333)]
INFO:detectron2.data.build:Removed 0 images with no usable annotations. 2 images left.
INFO:detectron2.data.build:Distribution of instances among all 1 categories:
|  category  | #instances   |
|:----------:|:-------------|
|    tree    | 67           |
|            |              |
INFO:detectron2.data.build:Using training sampler TrainingSampler
INFO:detectron2.data.common:Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
INFO:detectron2.data.common:Serializing 2 elements to byte tensors and concatenating them all ...
INFO:detectron2.data.common:Serialized dataset takes 0.10 MiB
INFO:detectron2.data.build:Making batched data loader with batch_size=2
WARNING:detectron2.solver.build:SOLVER.STEPS contains values larger than SOLVER.MAX_ITER. These values will be ignored.
INFO:detectron2.data.dataset_mapper:[DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=[1000, 1000], max_size=1333)]
INFO:__main__:[FlexibleDatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=[1000, 1000], max_size=1333)]
INFO:detectron2.data.build:Distribution of instances among all 1 categories:
|  category  | #instances   |
|:----------:|:-------------|
|    tree    | 40           |
|            |              |
INFO:detectron2.data.common:Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
INFO:detectron2.data.common:Serializing 1 elements to byte tensors and concatenating them all ...
INFO:detectron2.data.common:Serialized dataset takes 0.04 MiB
INFO:detectron2.checkpoint.detection_checkpoint:[DetectionCheckpointer] Loading from [D:/AI_MODELS/detectree2-models/230103_randresize_full.pth](file:///D:/AI_MODELS/detectree2-models/230103_randresize_full.pth) ...
INFO:fvcore.common.checkpoint:[Checkpointer] Loading from [d:/AI_MODELS/detectree2-models/230103_randresize_full.pth](file:///D:/AI_MODELS/detectree2-models/230103_randresize_full.pth) ...
INFO:__main__:Starting training from iteration 0
INFO:detectron2.utils.events: eta: 0:27:09  iter: 19  total_loss: 1.599  loss_cls: 0.3689  loss_box_reg: 0.6796  loss_mask: 0.3524  loss_rpn_cls: 0.1058  loss_rpn_loc: 0.07547    time: 0.5497  last_time: 0.5626  data_time: 0.1736  last_data_time: 0.0024   lr: 5.3944e-05  max_mem: 3390M
INFO:detectron2.utils.events: eta: 0:26:58  iter: 39  total_loss: 1.48  loss_cls: 0.3566  loss_box_reg: 0.6204  loss_mask: 0.3247  loss_rpn_cls: 0.09219  loss_rpn_loc: 0.07018    time: 0.5484  last_time: 0.5551  data_time: 0.0018  last_data_time: 0.0019   lr: 0.00011037  max_mem: 3390M
INFO:detectron2.utils.events: eta: 0:26:48  iter: 59  total_loss: 1.442  loss_cls: 0.3639  loss_box_reg: 0.6085  loss_mask: 0.3027  loss_rpn_cls: 0.07927  loss_rpn_loc: 0.05778    time: 0.5482  last_time: 0.5546  data_time: 0.0016  last_data_time: 0.0026   lr: 0.0001668  max_mem: 3390M
INFO:detectron2.utils.events: eta: 0:26:39  iter: 79  total_loss: 1.363  loss_cls: 0.3291  loss_box_reg: 0.5902  loss_mask: 0.2801  loss_rpn_cls: 0.08138  loss_rpn_loc: 0.07081    time: 0.5495  last_time: 0.5497  data_time: 0.0020  last_data_time: 0.0023   lr: 0.00022322  max_mem: 3390M
INFO:detectron2.data.dataset_mapper:[DatasetMapper] Augmentations used in inference: []
INFO:__main__:[FlexibleDatasetMapper] Augmentations used in inference: []
WARNING:detectron2.data.build:The following dataset names are not registered in the DatasetCatalog: {'D'}. Available datasets are KeysView(DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val, Danum_train, Danum_val))
ERROR:__main__:Exception during training:
Traceback (most recent call last):
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\catalog.py", line 51](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/catalog.py#line=50), in get
    f = self[name]
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\collections\__init__.py", line 1058](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/collections/__init__.py#line=1057), in __getitem__
    raise KeyError(key)
KeyError: 'D'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[C:\Users\AAmbarwari\AppData\Local\Temp\ipykernel_13000\1464463608.py", line 384](file:///C:/Users/AAmbarwari/AppData/Local/Temp/ipykernel_13000/1464463608.py#line=383), in train
    self.after_step()
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\train_loop.py", line 190](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/train_loop.py#line=189), in after_step
    h.after_step()
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\hooks.py", line 556](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/hooks.py#line=555), in after_step
    self._do_eval()
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\hooks.py", line 529](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/hooks.py#line=528), in _do_eval
    results = self._func()
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\defaults.py", line 489](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/defaults.py#line=488), in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\defaults.py", line 638](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/defaults.py#line=637), in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "[C:\Users\AAmbarwari\AppData\Local\Temp\ipykernel_13000\1464463608.py", line 562](file:///C:/Users/AAmbarwari/AppData/Local/Temp/ipykernel_13000/1464463608.py#line=561), in build_test_loader
    return build_detection_test_loader(cfg,
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\config\config.py", line 207](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/config/config.py#line=206), in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\config\config.py", line 245](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/config/config.py#line=244), in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\build.py", line 594](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/build.py#line=593), in _test_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\build.py", line 253](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/build.py#line=252), in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\build.py", line 253](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/build.py#line=252), in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "[C:\Users\AAmbarwari\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\catalog.py", line 53](file:///C:/Users/AAmbarwari/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/catalog.py#line=52), in get
    raise KeyError(
KeyError: "Dataset 'D' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val, Danum_train, Danum_val"
INFO:detectron2.engine.hooks:Overall training speed: 97 iterations in 0:00:54 (0.5569 s / it)
INFO:detectron2.engine.hooks:Total training time: 0:00:54 (0:00:00 on hooks)
INFO:detectron2.utils.events: eta: 0:26:30  iter: 99  total_loss: 1.302  loss_cls: 0.3122  loss_box_reg: 0.5709  loss_mask: 0.2711  loss_rpn_cls: 0.0669  loss_rpn_loc: 0.05625    time: 0.5512  last_time: 0.6917  data_time: 0.0018  last_data_time: 0.0020   lr: 0.00027965  max_mem: 3390M
No APs were recorded during training. Skipping model selection.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\catalog.py:51](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/catalog.py#line=50), in _DatasetCatalog.get(self, name)
     50 try:
---> 51     f = self[name]
     52 except KeyError as e:

File [~\anaconda3\envs\detectree2\lib\collections\__init__.py:1058](http://localhost:8888/~/anaconda3/envs/detectree2/lib/collections/__init__.py#line=1057), in UserDict.__getitem__(self, key)
   1057     return self.__class__.__missing__(self, key)
-> 1058 raise KeyError(key)

KeyError: 'D'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[8], line 3
      1 trainer = MyTrainer(cfg, patience=5)
      2 trainer.resume_or_load(resume=False)
----> 3 trainer.train()

Cell In[1], line 384, in MyTrainer.train(self)
    382 self.before_step()
    383 self.run_step()
--> 384 self.after_step()
    385 if self.early_stop:
    386     break

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\train_loop.py:190](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/train_loop.py#line=189), in TrainerBase.after_step(self)
    188 def after_step(self):
    189     for h in self._hooks:
--> 190         h.after_step()

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\hooks.py:556](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/hooks.py#line=555), in EvalHook.after_step(self)
    553 if self._period > 0 and next_iter % self._period == 0:
    554     # do the last eval in after_train
    555     if next_iter != self.trainer.max_iter:
--> 556         self._do_eval()

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\hooks.py:529](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/hooks.py#line=528), in EvalHook._do_eval(self)
    528 def _do_eval(self):
--> 529     results = self._func()
    531     if results:
    532         assert isinstance(
    533             results, dict
    534         ), "Eval function must return a dict. Got {} instead.".format(results)

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\defaults.py:489](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/defaults.py#line=488), in DefaultTrainer.build_hooks.<locals>.test_and_save_results()
    488 def test_and_save_results():
--> 489     self._last_eval_results = self.test(self.cfg, self.model)
    490     return self._last_eval_results

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\engine\defaults.py:638](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/engine/defaults.py#line=637), in DefaultTrainer.test(cls, cfg, model, evaluators)
    636 results = OrderedDict()
    637 for idx, dataset_name in enumerate(cfg.DATASETS.TEST):
--> 638     data_loader = cls.build_test_loader(cfg, dataset_name)
    639     # When evaluators are passed in as arguments,
    640     # implicitly assume that evaluators can be created before data_loader.
    641     if evaluators is not None:

Cell In[1], line 562, in MyTrainer.build_test_loader(cls, cfg, dataset_name)
    547 @classmethod
    548 def build_test_loader(cls, cfg, dataset_name):
    549     """
    550     Build the test data loader.
    551 
   (...)
    560         DataLoader: A data loader for the test dataset.
    561     """
--> 562     return build_detection_test_loader(cfg,
    563                                        dataset_name,
    564                                        mapper=FlexibleDatasetMapper(
    565                                            cfg, is_train=False))

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\config\config.py:207](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/config/config.py#line=206), in configurable.<locals>.wrapper.<locals>.wrapped(*args, **kwargs)
    204 @functools.wraps(orig_func)
    205 def wrapped(*args, **kwargs):
    206     if _called_with_cfg(*args, **kwargs):
--> 207         explicit_args = _get_args_from_config(from_config, *args, **kwargs)
    208         return orig_func(**explicit_args)
    209     else:

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\config\config.py:245](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/config/config.py#line=244), in _get_args_from_config(from_config_func, *args, **kwargs)
    243     if name not in supported_arg_names:
    244         extra_kwargs[name] = kwargs.pop(name)
--> 245 ret = from_config_func(*args, **kwargs)
    246 # forward the other arguments to __init__
    247 ret.update(extra_kwargs)

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\build.py:594](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/build.py#line=593), in _test_loader_from_config(cfg, dataset_name, mapper)
    591 if isinstance(dataset_name, str):
    592     dataset_name = [dataset_name]
--> 594 dataset = get_detection_dataset_dicts(
    595     dataset_name,
    596     filter_empty=False,
    597     proposal_files=(
    598         [
    599             cfg.DATASETS.PROPOSAL_FILES_TEST[list(cfg.DATASETS.TEST).index(x)]
    600             for x in dataset_name
    601         ]
    602         if cfg.MODEL.LOAD_PROPOSALS
    603         else None
    604     ),
    605 )
    606 if mapper is None:
    607     mapper = DatasetMapper(cfg, False)

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\build.py:253](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/build.py#line=252), in get_detection_dataset_dicts(names, filter_empty, min_keypoints, proposal_files, check_consistency)
    246     logger = logging.getLogger(__name__)
    247     logger.warning(
    248         "The following dataset names are not registered in the DatasetCatalog: "
    249         f"{names_set - available_datasets}. "
    250         f"Available datasets are {available_datasets}"
    251     )
--> 253 dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
    255 if isinstance(dataset_dicts[0], torchdata.Dataset):
    256     if len(dataset_dicts) > 1:
    257         # ConcatDataset does not work for iterable style dataset.
    258         # We could support concat for iterable as well, but it's often
    259         # not a good idea to concat iterables anyway.

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\build.py:253](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/build.py#line=252), in <listcomp>(.0)
    246     logger = logging.getLogger(__name__)
    247     logger.warning(
    248         "The following dataset names are not registered in the DatasetCatalog: "
    249         f"{names_set - available_datasets}. "
    250         f"Available datasets are {available_datasets}"
    251     )
--> 253 dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
    255 if isinstance(dataset_dicts[0], torchdata.Dataset):
    256     if len(dataset_dicts) > 1:
    257         # ConcatDataset does not work for iterable style dataset.
    258         # We could support concat for iterable as well, but it's often
    259         # not a good idea to concat iterables anyway.

File [~\anaconda3\envs\detectree2\lib\site-packages\detectron2\data\catalog.py:53](http://localhost:8888/~/anaconda3/envs/detectree2/lib/site-packages/detectron2/data/catalog.py#line=52), in _DatasetCatalog.get(self, name)
     51     f = self[name]
     52 except KeyError as e:
---> 53     raise KeyError(
     54         "Dataset '{}' is not registered! Available datasets are: {}".format(
     55             name, ", ".join(list(self.keys()))
     56         )
     57     ) from e
     58 return f()

KeyError: "Dataset 'D' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val, Danum_train, Danum_val"
```

**Comment by PatBall1** [comment]
You are encountering a KeyError: 'D' during the training process with detectree2. The error message indicates that the dataset named 'D' is not registered in the Detectron2 DatasetCatalog. This typically occurs if the code or configuration is attempting to load a dataset that the system doesn't recognize.

Look at the lines where you set:

```
trains = ("Danum_train")
tests = ("Danum_val")
```

Ensure these are tuples (note the comma for tuples is necessary if you intend a tuple):

```
trains = ("Danum_train",)
tests = ("Danum_val",)
```

Without the trailing comma, ("Danum_train") is actually a string, not a tuple. The code that sets cfg.DATASETS.TEST and cfg.DATASETS.TRAIN needs a tuple. Incorrectly formed tuples can lead to unexpected dataset name parsing.

**Comment by ambarwariagus** [comment]
Thank you very much Mr. @PatBall1, I missed that. Now, it's working.
